// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type TestEndpointInput struct {
	Request *string `json:"request,omitempty"`
}

type TestEndpointResponse struct {
	Response *string `json:"response,omitempty"`
}
