// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.9
// source: user_flights_mapping.proto

package datatypes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserFlightsMapping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string    `protobuf:"bytes,1,opt,name=id,proto3" json:"_id,omitempty" bson:"_id,omitempty"`
	User             *User     `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty" bson:"user,omitempty"`
	FavoritedFlights []*Flight `protobuf:"bytes,3,rep,name=favorited_flights,json=favoritedFlights,proto3" json:"favorited_flights,omitempty" bson:"favorited_flights,omitempty"`
	PurchasedFlights []*Flight `protobuf:"bytes,4,rep,name=purchased_flights,json=purchasedFlights,proto3" json:"purchased_flights,omitempty" bson:"purchased_flights,omitempty"`
}

func (x *UserFlightsMapping) Reset() {
	*x = UserFlightsMapping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_flights_mapping_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserFlightsMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFlightsMapping) ProtoMessage() {}

func (x *UserFlightsMapping) ProtoReflect() protoreflect.Message {
	mi := &file_user_flights_mapping_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFlightsMapping.ProtoReflect.Descriptor instead.
func (*UserFlightsMapping) Descriptor() ([]byte, []int) {
	return file_user_flights_mapping_proto_rawDescGZIP(), []int{0}
}

func (x *UserFlightsMapping) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserFlightsMapping) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserFlightsMapping) GetFavoritedFlights() []*Flight {
	if x != nil {
		return x.FavoritedFlights
	}
	return nil
}

func (x *UserFlightsMapping) GetPurchasedFlights() []*Flight {
	if x != nil {
		return x.PurchasedFlights
	}
	return nil
}

type PurchaseFlightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" bson:"user_id,omitempty"`
	FlightId string `protobuf:"bytes,2,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty" bson:"flight_id,omitempty"`
}

func (x *PurchaseFlightRequest) Reset() {
	*x = PurchaseFlightRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_flights_mapping_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PurchaseFlightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseFlightRequest) ProtoMessage() {}

func (x *PurchaseFlightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_flights_mapping_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseFlightRequest.ProtoReflect.Descriptor instead.
func (*PurchaseFlightRequest) Descriptor() ([]byte, []int) {
	return file_user_flights_mapping_proto_rawDescGZIP(), []int{1}
}

func (x *PurchaseFlightRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PurchaseFlightRequest) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

type PurchaseFlightResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PurchasedFlight *Flight `protobuf:"bytes,1,opt,name=purchased_flight,json=purchasedFlight,proto3" json:"purchased_flight,omitempty" bson:"purchased_flight,omitempty"`
}

func (x *PurchaseFlightResponse) Reset() {
	*x = PurchaseFlightResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_flights_mapping_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PurchaseFlightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseFlightResponse) ProtoMessage() {}

func (x *PurchaseFlightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_flights_mapping_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseFlightResponse.ProtoReflect.Descriptor instead.
func (*PurchaseFlightResponse) Descriptor() ([]byte, []int) {
	return file_user_flights_mapping_proto_rawDescGZIP(), []int{2}
}

func (x *PurchaseFlightResponse) GetPurchasedFlight() *Flight {
	if x != nil {
		return x.PurchasedFlight
	}
	return nil
}

type FavoriteFlightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" bson:"user_id,omitempty"`
	FlightId string `protobuf:"bytes,2,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty" bson:"flight_id,omitempty"`
}

func (x *FavoriteFlightRequest) Reset() {
	*x = FavoriteFlightRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_flights_mapping_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FavoriteFlightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteFlightRequest) ProtoMessage() {}

func (x *FavoriteFlightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_flights_mapping_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteFlightRequest.ProtoReflect.Descriptor instead.
func (*FavoriteFlightRequest) Descriptor() ([]byte, []int) {
	return file_user_flights_mapping_proto_rawDescGZIP(), []int{3}
}

func (x *FavoriteFlightRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FavoriteFlightRequest) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

type FavoriteFlightResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FavoritedFlight *Flight `protobuf:"bytes,1,opt,name=favorited_flight,json=favoritedFlight,proto3" json:"favorited_flight,omitempty" bson:"favorited_flight,omitempty"`
}

func (x *FavoriteFlightResponse) Reset() {
	*x = FavoriteFlightResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_flights_mapping_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FavoriteFlightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteFlightResponse) ProtoMessage() {}

func (x *FavoriteFlightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_flights_mapping_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteFlightResponse.ProtoReflect.Descriptor instead.
func (*FavoriteFlightResponse) Descriptor() ([]byte, []int) {
	return file_user_flights_mapping_proto_rawDescGZIP(), []int{4}
}

func (x *FavoriteFlightResponse) GetFavoritedFlight() *Flight {
	if x != nil {
		return x.FavoritedFlight
	}
	return nil
}

type GetPurchasedFlightsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" bson:"user_id,omitempty"`
}

func (x *GetPurchasedFlightsRequest) Reset() {
	*x = GetPurchasedFlightsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_flights_mapping_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPurchasedFlightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPurchasedFlightsRequest) ProtoMessage() {}

func (x *GetPurchasedFlightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_flights_mapping_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPurchasedFlightsRequest.ProtoReflect.Descriptor instead.
func (*GetPurchasedFlightsRequest) Descriptor() ([]byte, []int) {
	return file_user_flights_mapping_proto_rawDescGZIP(), []int{5}
}

func (x *GetPurchasedFlightsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPurchasedFlightsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flights []*Flight `protobuf:"bytes,1,rep,name=flights,proto3" json:"flights,omitempty" bson:"flights,omitempty"`
}

func (x *GetPurchasedFlightsResponse) Reset() {
	*x = GetPurchasedFlightsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_flights_mapping_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPurchasedFlightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPurchasedFlightsResponse) ProtoMessage() {}

func (x *GetPurchasedFlightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_flights_mapping_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPurchasedFlightsResponse.ProtoReflect.Descriptor instead.
func (*GetPurchasedFlightsResponse) Descriptor() ([]byte, []int) {
	return file_user_flights_mapping_proto_rawDescGZIP(), []int{6}
}

func (x *GetPurchasedFlightsResponse) GetFlights() []*Flight {
	if x != nil {
		return x.Flights
	}
	return nil
}

type GetFavoritedFlightsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" bson:"user_id,omitempty"`
}

func (x *GetFavoritedFlightsRequest) Reset() {
	*x = GetFavoritedFlightsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_flights_mapping_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFavoritedFlightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFavoritedFlightsRequest) ProtoMessage() {}

func (x *GetFavoritedFlightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_flights_mapping_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFavoritedFlightsRequest.ProtoReflect.Descriptor instead.
func (*GetFavoritedFlightsRequest) Descriptor() ([]byte, []int) {
	return file_user_flights_mapping_proto_rawDescGZIP(), []int{7}
}

func (x *GetFavoritedFlightsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetFavoritedFlightsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flights []*Flight `protobuf:"bytes,1,rep,name=flights,proto3" json:"flights,omitempty" bson:"flights,omitempty"`
}

func (x *GetFavoritedFlightsResponse) Reset() {
	*x = GetFavoritedFlightsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_flights_mapping_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFavoritedFlightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFavoritedFlightsResponse) ProtoMessage() {}

func (x *GetFavoritedFlightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_flights_mapping_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFavoritedFlightsResponse.ProtoReflect.Descriptor instead.
func (*GetFavoritedFlightsResponse) Descriptor() ([]byte, []int) {
	return file_user_flights_mapping_proto_rawDescGZIP(), []int{8}
}

func (x *GetFavoritedFlightsResponse) GetFlights() []*Flight {
	if x != nil {
		return x.Flights
	}
	return nil
}

type RecommendFlightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" bson:"user_id,omitempty"`
}

func (x *RecommendFlightRequest) Reset() {
	*x = RecommendFlightRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_flights_mapping_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecommendFlightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendFlightRequest) ProtoMessage() {}

func (x *RecommendFlightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_flights_mapping_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendFlightRequest.ProtoReflect.Descriptor instead.
func (*RecommendFlightRequest) Descriptor() ([]byte, []int) {
	return file_user_flights_mapping_proto_rawDescGZIP(), []int{9}
}

func (x *RecommendFlightRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RecommendFlightResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flights []*Flight `protobuf:"bytes,1,rep,name=flights,proto3" json:"flights,omitempty" bson:"flights,omitempty"`
}

func (x *RecommendFlightResponse) Reset() {
	*x = RecommendFlightResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_flights_mapping_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecommendFlightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendFlightResponse) ProtoMessage() {}

func (x *RecommendFlightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_flights_mapping_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendFlightResponse.ProtoReflect.Descriptor instead.
func (*RecommendFlightResponse) Descriptor() ([]byte, []int) {
	return file_user_flights_mapping_proto_rawDescGZIP(), []int{10}
}

func (x *RecommendFlightResponse) GetFlights() []*Flight {
	if x != nil {
		return x.Flights
	}
	return nil
}

var File_user_flights_mapping_proto protoreflect.FileDescriptor

var file_user_flights_mapping_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x5f, 0x6d,
	0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x5f, 0x6d, 0x61, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x1a, 0x0c, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbe, 0x01, 0x0a,
	0x12, 0x55, 0x73, 0x65, 0x72, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x4d, 0x61, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x12, 0x3b, 0x0a, 0x11, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x64,
	0x5f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x10,
	0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x64, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73,
	0x12, 0x3b, 0x0a, 0x11, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x64, 0x5f, 0x66, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x66, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x10, 0x70, 0x75, 0x72,
	0x63, 0x68, 0x61, 0x73, 0x65, 0x64, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x22, 0x4d, 0x0a,
	0x15, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x49, 0x64, 0x22, 0x53, 0x0a, 0x16,
	0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x10, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61,
	0x73, 0x65, 0x64, 0x5f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x52, 0x0f, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x64, 0x46, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x22, 0x4d, 0x0a, 0x15, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x46, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x49, 0x64,
	0x22, 0x53, 0x0a, 0x16, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x46, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x10, 0x66, 0x61,
	0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x64, 0x5f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x46, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x52, 0x0f, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x64, 0x46,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x22, 0x35, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x50, 0x75, 0x72, 0x63,
	0x68, 0x61, 0x73, 0x65, 0x64, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x1b,
	0x47, 0x65, 0x74, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x64, 0x46, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x66,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x66,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x07, 0x66, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x73, 0x22, 0x35, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x46, 0x61, 0x76, 0x6f,
	0x72, 0x69, 0x74, 0x65, 0x64, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x1b,
	0x47, 0x65, 0x74, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x64, 0x46, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x66,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x66,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x07, 0x66, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x73, 0x22, 0x31, 0x0a, 0x16, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x64, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x43, 0x0a, 0x17, 0x52, 0x65, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x46, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x52, 0x07, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x32, 0xdd, 0x04,
	0x0a, 0x19, 0x55, 0x73, 0x65, 0x72, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x4d, 0x61, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6b, 0x0a, 0x0e, 0x50,
	0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x12, 0x2b, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x5f, 0x6d, 0x61, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x46, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x5f, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x2e, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6b, 0x0a, 0x0e, 0x46, 0x61, 0x76, 0x6f,
	0x72, 0x69, 0x74, 0x65, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x12, 0x2b, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x5f, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x2e, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x66,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x5f, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x46,
	0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x7a, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x50, 0x75, 0x72, 0x63,
	0x68, 0x61, 0x73, 0x65, 0x64, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x12, 0x30, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x5f, 0x6d, 0x61, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x64,
	0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x5f, 0x6d, 0x61,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73,
	0x65, 0x64, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x7a, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65,
	0x64, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x12, 0x30, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x5f, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x2e,
	0x47, 0x65, 0x74, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x64, 0x46, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x5f, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x64, 0x46, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6e, 0x0a,
	0x0f, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x12, 0x2c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x5f,
	0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x64, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x5f, 0x6d, 0x61,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x46,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x28, 0x5a,
	0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x44, 0x61, 0x67, 0x6f,
	0x73, 0x75, 0x2f, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x41, 0x70, 0x70, 0x2f, 0x64, 0x61,
	0x74, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_flights_mapping_proto_rawDescOnce sync.Once
	file_user_flights_mapping_proto_rawDescData = file_user_flights_mapping_proto_rawDesc
)

func file_user_flights_mapping_proto_rawDescGZIP() []byte {
	file_user_flights_mapping_proto_rawDescOnce.Do(func() {
		file_user_flights_mapping_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_flights_mapping_proto_rawDescData)
	})
	return file_user_flights_mapping_proto_rawDescData
}

var file_user_flights_mapping_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_user_flights_mapping_proto_goTypes = []interface{}{
	(*UserFlightsMapping)(nil),          // 0: user_flights_mapping.UserFlightsMapping
	(*PurchaseFlightRequest)(nil),       // 1: user_flights_mapping.PurchaseFlightRequest
	(*PurchaseFlightResponse)(nil),      // 2: user_flights_mapping.PurchaseFlightResponse
	(*FavoriteFlightRequest)(nil),       // 3: user_flights_mapping.FavoriteFlightRequest
	(*FavoriteFlightResponse)(nil),      // 4: user_flights_mapping.FavoriteFlightResponse
	(*GetPurchasedFlightsRequest)(nil),  // 5: user_flights_mapping.GetPurchasedFlightsRequest
	(*GetPurchasedFlightsResponse)(nil), // 6: user_flights_mapping.GetPurchasedFlightsResponse
	(*GetFavoritedFlightsRequest)(nil),  // 7: user_flights_mapping.GetFavoritedFlightsRequest
	(*GetFavoritedFlightsResponse)(nil), // 8: user_flights_mapping.GetFavoritedFlightsResponse
	(*RecommendFlightRequest)(nil),      // 9: user_flights_mapping.RecommendFlightRequest
	(*RecommendFlightResponse)(nil),     // 10: user_flights_mapping.RecommendFlightResponse
	(*User)(nil),                        // 11: user.User
	(*Flight)(nil),                      // 12: flight.Flight
}
var file_user_flights_mapping_proto_depIdxs = []int32{
	11, // 0: user_flights_mapping.UserFlightsMapping.user:type_name -> user.User
	12, // 1: user_flights_mapping.UserFlightsMapping.favorited_flights:type_name -> flight.Flight
	12, // 2: user_flights_mapping.UserFlightsMapping.purchased_flights:type_name -> flight.Flight
	12, // 3: user_flights_mapping.PurchaseFlightResponse.purchased_flight:type_name -> flight.Flight
	12, // 4: user_flights_mapping.FavoriteFlightResponse.favorited_flight:type_name -> flight.Flight
	12, // 5: user_flights_mapping.GetPurchasedFlightsResponse.flights:type_name -> flight.Flight
	12, // 6: user_flights_mapping.GetFavoritedFlightsResponse.flights:type_name -> flight.Flight
	12, // 7: user_flights_mapping.RecommendFlightResponse.flights:type_name -> flight.Flight
	1,  // 8: user_flights_mapping.UserFlightsMappingService.PurchaseFlight:input_type -> user_flights_mapping.PurchaseFlightRequest
	3,  // 9: user_flights_mapping.UserFlightsMappingService.FavoriteFlight:input_type -> user_flights_mapping.FavoriteFlightRequest
	5,  // 10: user_flights_mapping.UserFlightsMappingService.GetPurchasedFlights:input_type -> user_flights_mapping.GetPurchasedFlightsRequest
	7,  // 11: user_flights_mapping.UserFlightsMappingService.GetFavoritedFlights:input_type -> user_flights_mapping.GetFavoritedFlightsRequest
	9,  // 12: user_flights_mapping.UserFlightsMappingService.RecommendFlight:input_type -> user_flights_mapping.RecommendFlightRequest
	2,  // 13: user_flights_mapping.UserFlightsMappingService.PurchaseFlight:output_type -> user_flights_mapping.PurchaseFlightResponse
	4,  // 14: user_flights_mapping.UserFlightsMappingService.FavoriteFlight:output_type -> user_flights_mapping.FavoriteFlightResponse
	6,  // 15: user_flights_mapping.UserFlightsMappingService.GetPurchasedFlights:output_type -> user_flights_mapping.GetPurchasedFlightsResponse
	8,  // 16: user_flights_mapping.UserFlightsMappingService.GetFavoritedFlights:output_type -> user_flights_mapping.GetFavoritedFlightsResponse
	10, // 17: user_flights_mapping.UserFlightsMappingService.RecommendFlight:output_type -> user_flights_mapping.RecommendFlightResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_user_flights_mapping_proto_init() }
func file_user_flights_mapping_proto_init() {
	if File_user_flights_mapping_proto != nil {
		return
	}
	file_flight_proto_init()
	file_user_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_user_flights_mapping_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserFlightsMapping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_flights_mapping_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PurchaseFlightRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_flights_mapping_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PurchaseFlightResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_flights_mapping_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FavoriteFlightRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_flights_mapping_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FavoriteFlightResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_flights_mapping_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPurchasedFlightsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_flights_mapping_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPurchasedFlightsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_flights_mapping_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFavoritedFlightsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_flights_mapping_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFavoritedFlightsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_flights_mapping_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecommendFlightRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_flights_mapping_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecommendFlightResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_flights_mapping_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_flights_mapping_proto_goTypes,
		DependencyIndexes: file_user_flights_mapping_proto_depIdxs,
		MessageInfos:      file_user_flights_mapping_proto_msgTypes,
	}.Build()
	File_user_flights_mapping_proto = out.File
	file_user_flights_mapping_proto_rawDesc = nil
	file_user_flights_mapping_proto_goTypes = nil
	file_user_flights_mapping_proto_depIdxs = nil
}
